# Generated by Django 2.1.1 on 2018-10-30 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20181030_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admin',
            unique_together={('organization', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
