# Generated by Django 2.1.1 on 2018-11-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_game_group'),
        ('organization', '0004_auto_20181031_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='quizzes',
            field=models.ManyToManyField(to='api.Quiz'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
