# Generated by Django 2.1.1 on 2018-10-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181020_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0, help_text='Начисленные очки за ответ.'),
        ),
        migrations.AddField(
            model_name='game',
            name='base_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='online',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
