# Generated by Django 2.1.1 on 2018-10-22 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181020_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='ID правильных вариантов ответов.\nДля Single вопросов массив состоит из одного элемента.\nДля Sequence важен порядок.\nПри создании викторины указывать порядковый номер в массиве вариантов (номер начинается с 1).', size=None),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game')},
        ),
    ]
