# Generated by Django 2.1.1 on 2018-10-28 22:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181022_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=0, help_text='Рейтинг за игру.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='ID правильных вариантов ответов.\nДля Single вопросов массив состоит из одного элемента.\nДля Sequence важен порядок.\nПри создании и изменении викторины указывать порядковый номер в массиве вариантов (номер начинается с 1).', size=None),
        ),
    ]
